import CtaHowItWorks from "@/domains/other-externals/components/community-cta";
import CreateAds from "@/domains/other-externals/components/key-features-ad";
import FeaturesHero from "@/domains/other-externals/components/key-features-hero-section";
import Image from "next/image";

const notes = [
  {
    name: "Publish to Community",
    description:
      "Publish your generated ad to Genz.ad community by simply clicking save and publish.",
  },
  {
    name: "Explore Community",
    description:
      "Dive into the Genz.ad community to discover, engage with, and be inspired by ads created by others.",
  },
];

const Community = () => {
  return (
    <div className="bg-gradient-to-b from-[#F9F9F9] to-white to-24.5  md:px-5 flex flex-col gap-6">
      <FeaturesHero
        heading={
          <>
            Explore Genz.ad <br />
            <span className="text-[#B800B8] ml-2 font-semibold">community</span>
          </>
        }
        subHeading="Explore ads generated by others, get inspired, and share your own
          creations. The Genz.ad Community is your hub for exploring and reusing
          innovative AI-powered ad templates, making ad creation faster and more
          impactful."
        buttonText="Explore our Community"
      />
      <div className="max-w-7xl w-full xl:mx-auto max-lg:px-4 pt-8 flex flex-col gap-6 lg:gap-14">
        <div className="relative w-full aspect-square h-[200px] md:h-[500px] lg:h-[600px]">
          <Image
            src="/communityimg.svg"
            alt="community"
            fill
            priority
            className="xl:object-cover object-contain w-full h-full"
          />
        </div>
        <CreateAds
          heading={
            <>
              How to use Genz.ad <br /> community
            </>
          }
          notes={notes}
        />
        <CtaHowItWorks />
      </div>
    </div>
  );
};

export default Community;
