"use client";
import { motion } from "framer-motion";
import AnimatedButton from "./animated-button";
import { useAuthStore } from "@/store/auth-store";

export default function CommunityHero() {
  const token = useAuthStore((state) => state.token);

  return (
    <section className="w-full items-center justify-center  flex">
      <motion.div
        className="relative z-10 max-w-[1037px] w-full px-4 mt-16 md:mt-[120px] text-center"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        exit={{ opacity: 0, y: -20 }}
      >
        <motion.h1
          className="text-3xl md:text-[56px] font-medium text-[#121316] tracking-tight mb-4 lg:max-w-[40rem] lg:px-10  text-center lg:mx-auto"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.15, duration: 0.5 }}
        >
          Join the Genz.ad <br />
          <span className="text-[#B800B8] ml-2 font-semibold">community</span>
        </motion.h1>
        <motion.p
          className="text-lg text-[#16151e] mb-6"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3, duration: 0.5 }}
        >
          Explore ads generated by others, get inspired, and share your own
          creations. The Genz.ad Community is your hub for exploring and reusing
          innovative AI-powered ad templates, making ad creation faster and more
          impactful.
        </motion.p>
        <div className="flex gap-4 md:gap-10 flex-col md:flex-row justify-center">
          <AnimatedButton
            href={token ? "dashboard" : "/signin?type=signin"}
            text="Explore Community"
            variant="primary"
          />
        </div>
      </motion.div>
    </section>
  );
}
